---
title: "Advanced Normalization Tools: <br> Examples that answer FAQs"
author: "Brian B. Avants"
date: "`r Sys.Date()`"
output: html_document
---

# Introduction

[Advanced Normalization Tools](https://github.com/stnava/ANTs) uses [github](www.github.com) to organize and 
distribute simple, reproducible examples.   We also provide a [wiki](https://github.com/stnava/ANTs/wiki).

# Wiki examples

| Short name |  link  |   Comments |
|---|---|---|
| antscall| https://github.com/stnava/ANTs/wiki/Anatomy-of-an-antsRegistration-call | details what the ants command line means |
| antsvers |  https://github.com/stnava/ANTs/wiki/ANTs-version-information |  identify your ants version |
| act |  https://github.com/stnava/ANTs/wiki/antsCorticalThickness-and-antsLongitudinalCorticalThickness-output |  what do these programs ants\*CorticalThickness.sh produce? |
| build |  https://github.com/stnava/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS |  how do i build ants?   |
| nifti |  https://github.com/stnava/ANTs/wiki/How-does-ANTs-handle-qform-and-sform-in-NIFTI-1-images%3F |  How does ANTs handle qform and sform in NIFTI 1 images? |
| amzn |  https://github.com/stnava/ANTs/wiki/Install-ANTs-on-Amazon |  Can I install ANTs on Amazon? |
| regerr |  https://github.com/stnava/ANTs/wiki/My-registration-fails-with-an-error | How do I interpret a registration error?  |
| orient | https://github.com/stnava/ANTs/wiki/Output-images-have-incorrect-orientation-or-origin  |  Why is my image orientation incorrect? |
| mmm |  https://github.com/stnava/ANTs/wiki/simple-case:-T1-to-MNI-mapping-for-both-structure-and-pre-registered-fMRI |  Brief multiple modality mapping of fMRI to a template space via transform concatenation |
| regFAQ |  https://github.com/stnava/ANTs/wiki/Tips-for-improving-registration-results | Registration FAQ  |
|  snap |  https://github.com/stnava/ANTs/wiki/Using-ITK-SNAP-with-ANTs |  ITK-snap suggestions  |
| DTI |  https://github.com/stnava/ANTs/wiki/Warp-and-reorient-a-diffusion-tensor-image |  transform DTI |
| RegMask | https://github.com/ntustison/antsRegistrationWithMaskExample/blob/master/antsRegistrationExampleCommand.sh | ``antsRegistration`` with mask |
|  |   |   |


# Links to github examples with brief comments

These are different than wiki examples in that they come with data.

A user interested in these examples should *clone* the repository via *git*.  

```{bash,eval=FALSE}
git clone reponame.git
```

The repository will should you how to do this, otherwise search for the answer from the cloud.


| Short name |  link  |   Comments |
|---|---|---|
| chicken  | https://github.com/stnava/chicken  |  mapping points and global optimization  |   
| template  | https://github.com/ntustison/TemplateBuildingExample  |  build an optimal template as in many different <br> ants papers that allow large-scale brain mapping  |   
| visualization  | https://github.com/ntustison/antsVisualizationExamples | volumetric and surface-based rendering for images and overlays |
| ICA-eigenanatomy | https://github.com/stnava/blindSourceSeparationInANTsR | Reproduces a classic example in blind source separation and shows how to link with eigenanatomy |
| BBM | https://github.com/stnava/BasicBrainMapping |  A simple and "fast" brain registration example |
| jacobian | https://github.com/stnava/jacobianTests |  very basic test of jacobian |
| sccan | https://github.com/stnava/sccanTutorial | introduction to sparse canonical correlation analysis statistical studies - may be slightly out of date |
| RMI | https://github.com/stnava/RMI | R in medical imaging tutorial material |
| RMID | https://github.com/stnava/RMI_Data |  data for RMI |
| morphing | https://github.com/stnava/Morpheus | morphing example with antsRegistration |
| ASL | https://github.com/stnava/antsASLProcessing |  arterial spin labeling (ASL) processing pipeline using ANTs. |
| ANTsDoc | https://github.com/stnava/ANTsDoc |  Documentation for ANTs |
| ANTsMM | https://github.com/stnava/ANTS_MultiModality | older talk on multiple modality ANTs processing |
| fMRIANTs | https://github.com/stnava/fMRIANTs |  Minimal fMRI pre-processing with ANTS, may be slightly out of date |
| featureMatching | https://github.com/stnava/featureMatching | old example of SIFT-like feature matching, subsumed by antsAI |
| NB | https://github.com/stnava/NeuroBattery |  Using ANTs to process multiple MR image types for a single subject |
| Eanat1 | https://github.com/stnava/eigenanatomy1 |  basic eigenanatomy example in aging |
| Asym | https://github.com/stnava/asymmetry | asymmetry analysis with ANTs |
| C | https://github.com/stnava/C |  "C"lassic large deformation example |
| PTBP | https://github.com/stnava/PediatricTemplateOfBrainPerfusion |  analysis in PTBP paper |
| butterfly | https://github.com/stnava/butterfly |  multi-start registration example |
| Haxby | https://github.com/stnava/Haxby2001 | reproduce face recognition decoding results (may be out of date but could be revived with small efforts) |
| rfmri | https://github.com/stnava/RfMRI |  fmri processing examples in ANTsR (may be out of date but could be revived with small efforts) |
| cars | https://github.com/stnava/cars |  an old example mapping between an american and german vehicle |
| antsTut | https://github.com/stnava/ANTsTutorial | evolving tutorial materials |
| visualization | https://github.com/ntustison/antsVisualizationExamples | Examples for ``antsSurf``, ``antsVol``, and ``CreateTiledMosaic``|
| template | https://github.com/ntustison/TemplateBuildingExample | Template building examples (brain and faces) |
| antsCT | https://github.com/ntustison/antsCorticalThicknessExample | 2-D ``antsCorticalThickness.sh`` examples. |
| antsJLF | https://github.com/ntustison/MalfLabelingExample | joint label fusion example. |
| antsBrainExtraction | https://github.com/ntustison/antsBrainExtractionExample | Example for ``antsBrainExtraction.sh`` |
| antsAtroposN4 | https://github.com/ntustison/antsAtroposN4Example | Example for ``antsAtroposN4.sh`` |
| lungReg | https://github.com/ntustison/antsCtLungRegistrationExample | Combine separate left/right lung registrations |
| lobeLungJLF | https://github.com/ntustison/LungAndLobeEstimationExample | Use JLF to estimate lung and lobes |
| LungRegMask | https://github.com/ntustison/ProtonCtLungMaskRegistration | Register lung masks from CT and MRI |
| | | |
