---
title: "Simulate a deformation field with ANTsR"
author: "Brian B. Avants, Jeffrey T. Duda"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
    %\VignetteEngine{knitr::rmarkdown}
    %\VignetteIndexEntry{mrvnrfs}
    \usepackage[utf8]{inputenc}
---


```{r simdef}
library( ANTsR )
aa = antsImageRead( "/tmp/seg.nii.gz", 2 )
aaDist = iMath( aa, "MaurerDistance") + rnorm( sum( aa>=0  ), sd=5 )
plot( aaDist )
bb = iMath( aa, "MD", 5 )
areg = antsRegistration( aa, aaDist * bb, typeofTransform = "SyNOnly",
  synMetric = "demons", synIterations = 15, 
  flowSigma = 6, totalSigma = 3,
  gradStep = 0.2 )
img    = antsImageRead( getANTsRData( "r16" ) )
field  = antsImageRead( areg$fwdtransforms[ 1 ] )
warpTx = antsrTransformFromDisplacementField( field )
warped = applyAntsrTransform( warpTx, data = img, reference = img)
field  = antsImageRead( areg$fwdtransforms[ 1 ] )
warpTx = antsrTransformFromDisplacementField( field )
txlist = list( )
ncomp = 6
for ( i in 1:ncomp ) txlist[[ i ]] = warpTx
warped = applyAntsrTransform( 
  txlist, data = img, reference = img)
```

Look.

```{r viewdef}
plot( img )
plot( warped )
```

Grid.

```{r viewgrid}
f = areg$fwdtransforms[ 1 ]
grid = createWarpedGrid( img, gridStep = 10, gridWidth = 2,
  fixedReferenceImage = img, transform = rep( f, ncomp ) )
plot( grid )
```
